language: php

php:
#  - 5.5
#  - 5.6
  - 7.0
#  - nightly
#  - hhvm

#matrix:
#  allow_failures:
#    - php: nightly

env:
  - LARAVEL_VERSION="5.1.*" TESTBENCH_VERSION="3.1.*"
#  - LARAVEL_VERSION="5.2.*" TESTBENCH_VERSION="3.2.*"
#  - LARAVEL_VERSION="5.3.*" TESTBENCH_VERSION="3.3.*"

addons:
  apt:
    packages:
    - pngquant
    - gifsicle
    - jpegoptim

before_install:
#  - sudapt-get -y update
#  - apt-get -y upgrade
#  - sudo apt-get install -y pngquant gifsicle jpegoptim
  - cd /tmp && wget https://lagerlogistik-azubi.de/sites/lagerlogistik-azubi.de/files/head.png
  - ls -la /tmp/
  - cd /tmp && pngquant head.png
  - ls -la /tmp/
#  - which pngquant
#  - which gifsicle
#  - which jpegoptim

before_script:
  - composer self-update
  - composer require orchestra/testbench:"$TESTBENCH_VERSION" illuminate/support:"$LARAVEL_VERSION"
  - composer install

script: phpunit --coverage-text

sudo: false
