language: php

sudo: true

php:
#  - 5.5
#  - 5.6
  - 7.0
#  - nightly
#  - hhvm

#matrix:
#  allow_failures:
#    - php: nightly

env:
  - LARAVEL_VERSION="5.1.*" TESTBENCH_VERSION="3.1.*"
#  - LARAVEL_VERSION="5.2.*" TESTBENCH_VERSION="3.2.*"
#  - LARAVEL_VERSION="5.3.*" TESTBENCH_VERSION="3.3.*"

#addons:
#  apt:
#    packages:
#    - pngquant
#    - gifsicle
#    - jpegoptim
#
#    before_install:


before_install:
#  - wget http://de.archive.ubuntu.com/ubuntu/pool/universe/p/pngquant/pngquant_2.5.0-1_amd64.deb
  - wget http://ftp.de.debian.org/debian/pool/main/p/pngquant/pngquant_2.5.0-1+b1_amd64.deb
  - sudo dpkg -i pngquant_2.5.0-1+b1_amd64.deb

  - wget http://ftp.de.debian.org/debian/pool/main/g/gifsicle/gifsicle_1.88-1_amd64.deb
  - sudo dpkg -i gifsicle_1.88-1_amd64.deb

  - wget http://ftp.de.debian.org/debian/pool/main/j/jpegoptim/jpegoptim_1.4.3-1_amd64.deb
  - sudo dpkg -i jpegoptim_1.4.3-1_amd64.deb


#  - sudo apt-get install -y jpegoptim

  - pngquant --version # 2.5.0 (June 2015)
  - jpegoptim --version # jpegoptim v1.4.3  x86_64-pc-linux-gnu (libjpeg version: 8d  15-Jan-2012)
  - gifsicle --version # LCDF Gifsicle 1.88
#  - sudapt-get -y update
#  - apt-get -y upgrade
#  - sudo apt-get install -y pngquant gifsicle jpegoptim
#  - cd /tmp && wget https://lagerlogistik-azubi.de/sites/lagerlogistik-azubi.de/files/head.png --no-check-certificate
#  - ls -la /tmp/
#  - cd /tmp && pngquant head.png
#  - ls -la /tmp/
#  - which pngquant
#  - which gifsicle
#  - which jpegoptim

before_script:
  - composer self-update
  - composer require orchestra/testbench:"$TESTBENCH_VERSION" illuminate/support:"$LARAVEL_VERSION"
  - composer install

script: phpunit --coverage-text